version: "3.5"

services:
  php:
    container_name: "php_backend"
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/

  apache:
    container_name: "apache_frontend"
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/

  mysql:
    container_name: "mysql_db"
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  frontend:
  backend: